export const dom = {
  bookmarkForm: document.querySelector("#bookmark-form"),
  articleUrl: document.querySelector("#article-url"),
  experimentalReaderToggle: document.querySelector(
    "#experimental-reader-toggle",
  ),
  articleTags: document.querySelector("#article-tags"),
  articleProjects: document.querySelector("#article-projects"),
  availableTags: document.querySelector("#available-tags"),
  availableProjects: document.querySelector("#available-projects"),
  fetchStatus: document.querySelector("#fetch-status"),
  libraryArticlesTitle: document.querySelector("#library-articles-title"),
  articleList: document.querySelector("#article-list"),
  libraryTagFilters: document.querySelector("#library-tag-filters"),
  libraryTagClear: document.querySelector("#library-tag-clear"),
  libraryProjectFilters: document.querySelector("#library-project-filters"),
  libraryProjectClear: document.querySelector("#library-project-clear"),
  readerBackButton: document.querySelector("#reader-back-button"),
  readerTitle: document.querySelector("#reader-title"),
  readerMeta: document.querySelector("#reader-meta"),
  readerSurface: document.querySelector("#reader-surface"),
  selectionMenu: document.querySelector("#selection-menu"),
  highlightSelectionButton: document.querySelector(
    "#highlight-selection-button",
  ),
  noteSelectionButton: document.querySelector("#note-selection-button"),
  shareSelectionButton: document.querySelector("#share-selection-button"),
  highlightList: document.querySelector("#highlight-list"),
  readerSideTabs: [...document.querySelectorAll("[data-reader-side-tab]")],
  readerSidePaneHighlights: document.querySelector(
    "#reader-side-pane-highlights",
  ),
  readerSidePaneNext: document.querySelector("#reader-side-pane-next"),
  rssReaderNext: document.querySelector("#rss-reader-next"),
  tabButtons: [...document.querySelectorAll("[data-tab-target]")],
  tabPanels: [...document.querySelectorAll(".tab-panel")],
  addArticleDialog: document.querySelector("#add-article-dialog"),
  projectForm: document.querySelector("#project-form"),
  projectName: document.querySelector("#project-name"),
  projectDescription: document.querySelector("#project-description"),
  projectSettingsList: document.querySelector("#project-settings-list"),
  projectList: document.querySelector("#project-list"),
  projectsProjectFilters: document.querySelector("#projects-project-filters"),
  projectsProjectClear: document.querySelector("#projects-project-clear"),
  projectsLibraryPanel: document.querySelector("#projects-library-panel"),
  projectsTitle: document.querySelector("#projects-title"),
  projectEditorPanel: document.querySelector("#project-editor-panel"),
  projectBackButton: document.querySelector("#project-back-button"),
  projectToggleMarkdownButton: document.querySelector(
    "#project-toggle-markdown-button",
  ),
  projectStageMenuButton: document.querySelector("#project-stage-menu-button"),
  projectStageMenuLabel: document.querySelector("#project-stage-menu-label"),
  projectStageMenuList: document.querySelector("#project-stage-menu-list"),
  projectStageMenuOptions: [
    ...document.querySelectorAll("[data-project-stage-option]"),
  ],
  projectLinkPopover: document.querySelector("#project-link-popover"),
  projectLinkInput: document.querySelector("#project-link-input"),
  projectLinkCancelButton: document.querySelector(
    "#project-link-cancel-button",
  ),
  projectLinkApplyButton: document.querySelector("#project-link-apply-button"),
  projectEditorContent: document.querySelector("#project-editor-content"),
  projectEditorPreview: document.querySelector("#project-editor-preview"),
  projectSidebarTopbar: document.querySelector("#project-sidebar-topbar"),
  projectSidebarBackButton: document.querySelector(
    "#project-sidebar-back-button",
  ),
  projectSidebarTitle: document.querySelector("#project-sidebar-title"),
  projectSidebarMeta: document.querySelector("#project-sidebar-meta"),
  projectHighlightList: document.querySelector("#project-highlight-list"),
  settingsNavButtons: [...document.querySelectorAll("[data-settings-section]")],
  settingsPanels: [...document.querySelectorAll("[data-settings-panel]")],
  exportMarkdownFolderButton: document.querySelector(
    "#export-markdown-folder-button",
  ),
  exportMarkdownStatus: document.querySelector("#export-markdown-status"),
  settingsStorageRefreshButton: document.querySelector(
    "#settings-storage-refresh-button",
  ),
  settingsStorageSummary: document.querySelector("#settings-storage-summary"),
  settingsStorageBreakdown: document.querySelector(
    "#settings-storage-breakdown",
  ),
  deleteAllDataButton: document.querySelector("#delete-all-data-button"),
  displayFontButtons: [...document.querySelectorAll("[data-display-font]")],
  displayThemeButtons: [...document.querySelectorAll("[data-display-theme]")],
  displayHighlightButtons: [
    ...document.querySelectorAll("[data-display-highlight]"),
  ],
  rssRetentionSelect: document.querySelector("#rss-retention-select"),
  rssAutoRefreshSelect: document.querySelector("#rss-auto-refresh-select"),
  rssSettingsLastFetched: document.querySelector("#rss-settings-last-fetched"),
  tagForm: document.querySelector("#tag-form"),
  tagName: document.querySelector("#tag-name"),
  tagList: document.querySelector("#tag-list"),
  autoTagEnabled: document.querySelector("#auto-tag-enabled"),
  autoTagUseDefaultCountries: document.querySelector(
    "#auto-tag-use-default-countries",
  ),
  autoTagRuleForm: document.querySelector("#auto-tag-rule-form"),
  autoTagRuleTag: document.querySelector("#auto-tag-rule-tag"),
  autoTagRuleKeywords: document.querySelector("#auto-tag-rule-keywords"),
  autoTagRulesList: document.querySelector("#auto-tag-rules-list"),
  autoTagImportInput: document.querySelector("#auto-tag-import-input"),
  autoTagImportButton: document.querySelector("#auto-tag-import-button"),
  rssSubscribeForm: document.querySelector("#rss-subscribe-form"),
  rssSubscribePopover: document.querySelector("#rss-subscribe-popover"),
  rssOpenSubscribeButton: document.querySelector("[data-rss-open-subscribe]"),
  rssCloseSubscribeButton: document.querySelector("[data-rss-close-subscribe]"),
  rssRefreshActiveButton: document.querySelector("[data-rss-refresh-active]"),
  rssLastUpdated: document.querySelector("#rss-last-updated"),
  rssFeedUrlInput: document.querySelector("#rss-feed-url-input"),
  rssFeedFolderInput: document.querySelector("#rss-feed-folder-input"),
  rssFolderSuggestions: document.querySelector("#rss-folder-suggestions"),
  rssFolderList: document.querySelector("#rss-folder-list"),
  rssFeedList: document.querySelector("#rss-feed-list"),
  rssItems: document.querySelector("#rss-items"),
};
